id: 433b0a688d564809a929382b68884a64
initial_creation_type: ocr
source_metadata:
  volumes:
    ee94d5ae9c214acb878c0179355c17ca:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
